"""Add Follow table

Revision ID: 3b7c47021635
Revises: ae961db29a50
Create Date: 2023-12-30 19:27:15.699118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b7c47021635'
down_revision = 'ae961db29a50'
branch_labels = None
depends_on = None


def upgrade():
    # Add the new column without NOT NULL constraint
    op.add_column('user', sa.Column('date_joined', sa.DateTime(), nullable=True, default=None))

    # Update existing rows with a non-NULL value
    op.execute('UPDATE user SET date_joined = CURRENT_TIMESTAMP')

    # Modify the column to set it as NOT NULL
    op.execute('PRAGMA foreign_keys=off;')
    op.execute('BEGIN TRANSACTION;')
    op.execute('CREATE TEMPORARY TABLE user_backup(id, username, email, password, date_joined);')
    op.execute('INSERT INTO user_backup SELECT id, username, email, password, date_joined FROM user;')
    op.execute('DROP TABLE user;')
    op.execute('CREATE TABLE user(id INTEGER NOT NULL, username VARCHAR(20) NOT NULL, email VARCHAR(120) NOT NULL, password VARCHAR(60) NOT NULL, date_joined DATETIME NOT NULL, PRIMARY KEY (id));')
    op.execute('INSERT INTO user SELECT id, username, email, password, date_joined FROM user_backup;')
    op.execute('DROP TABLE user_backup;')
    op.execute('COMMIT;')
    op.execute('PRAGMA foreign_keys=on;')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date_joined')

    # ### end Alembic commands ###
